version: "3.8"
services:
  # Applications
  
  catalog-service:
    depends_on:
      - polar-postgres
    image: "catalog-service"
    ports:
      - 9001:9001
    environment:
      # JVM 스택에서 메모리를 할당할 스레드 수 설정
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata

  # Backing Services

  polar-postgres:
    image: "postgres:14.12"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog
